// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const countCompletedTodos = `-- name: CountCompletedTodos :one
SELECT COUNT(*) FROM todos
WHERE completed = 1 AND user_id = ?
`

func (q *Queries) CountCompletedTodos(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCompletedTodos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodos = `-- name: CountTodos :one
SELECT COUNT(*) FROM todos
WHERE user_id = ?
`

func (q *Queries) CountTodos(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodos, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (id, user_id, text, completed, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, text, completed, created_at
`

type CreateTodoParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Text      string    `json:"text"`
	Completed bool      `json:"completed"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.Completed,
		arg.CreatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompletedTodos = `-- name: DeleteCompletedTodos :exec
DELETE FROM todos
WHERE completed = 1 AND user_id = ?
`

func (q *Queries) DeleteCompletedTodos(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteCompletedTodos, userID)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ? AND user_id = ?
`

type DeleteTodoParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, user_id, text, completed, created_at FROM todos
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAllTodos(ctx context.Context, userID string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, text, completed, created_at FROM todos
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetTodoByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByID, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const updateTodoCompleted = `-- name: UpdateTodoCompleted :exec
UPDATE todos
SET completed = ?
WHERE id = ? AND user_id = ?
`

type UpdateTodoCompletedParams struct {
	Completed bool   `json:"completed"`
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) UpdateTodoCompleted(ctx context.Context, arg UpdateTodoCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoCompleted, arg.Completed, arg.ID, arg.UserID)
	return err
}
