package main

import (
	"log"
	"net/http"
	"os"
	"time"

	"github.com/livetemplate/lvt/components/base"
	"github.com/livetemplate/lvt/components/modal"
	"github.com/livetemplate/lvt/components/toast"
	"github.com/livetemplate/lvt/components/toggle"
	"github.com/livetemplate/livetemplate"
	e2etest "github.com/livetemplate/lvt/testing"
)

// Todo represents a single todo item.
type Todo struct {
	ID        int
	Title     string
	Completed *toggle.Checkbox
}

// TodoState holds the application state.
type TodoState struct {
	Title         string
	Todos         []Todo
	NewTodoTitle  string
	Toasts        *toast.Container
	DeleteConfirm *modal.ConfirmModal
	DeleteID      int // ID of todo pending deletion
	NextID        int // Must be exported for JSON serialization
}

// TodoController handles todo actions.
type TodoController struct{}

// AddTodo handles the "add_todo" action.
func (c *TodoController) AddTodo(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	title := ctx.GetString("title")
	if title == "" {
		state.Toasts.AddWarning("Warning", "Please enter a todo title")
		return state, nil
	}

	state.NextID++
	newTodo := Todo{
		ID:    state.NextID,
		Title: title,
		Completed: toggle.NewCheckbox("todo-"+itoa(state.NextID),
			toggle.WithCheckboxLabel(title),
		),
	}
	state.Todos = append(state.Todos, newTodo)
	state.NewTodoTitle = ""
	state.Toasts.AddSuccess("Added", "Todo added successfully")
	return state, nil
}

// ToggleTodo handles toggle_todo-{id} actions (checkbox change events).
func (c *TodoController) ToggleTodo(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	idStr := ctx.GetString("id")
	id := atoi(idStr)

	for i := range state.Todos {
		if state.Todos[i].ID == id {
			state.Todos[i].Completed.Toggle()
			if state.Todos[i].Completed.Checked {
				state.Toasts.AddInfo("Completed", "Todo marked as complete")
			} else {
				state.Toasts.AddInfo("Reopened", "Todo marked as incomplete")
			}
			break
		}
	}
	return state, nil
}

// ConfirmDelete handles the "confirm_delete" action - shows confirmation modal.
func (c *TodoController) ConfirmDelete(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	idStr := ctx.GetString("id")
	state.DeleteID = atoi(idStr)
	state.DeleteConfirm.Show()
	return state, nil
}

// ConfirmDeleteConfirm handles the "confirm_delete_confirm" action from modal.
func (c *TodoController) ConfirmDeleteConfirm(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	// Find and remove the todo
	for i := range state.Todos {
		if state.Todos[i].ID == state.DeleteID {
			state.Todos = append(state.Todos[:i], state.Todos[i+1:]...)
			state.Toasts.AddSuccess("Deleted", "Todo deleted successfully")
			break
		}
	}
	state.DeleteConfirm.Hide()
	state.DeleteID = 0
	return state, nil
}

// CancelDeleteConfirm handles the "cancel_delete_confirm" action from modal.
func (c *TodoController) CancelDeleteConfirm(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	state.DeleteConfirm.Hide()
	state.DeleteID = 0
	return state, nil
}

// DismissToastNotifications handles "dismiss_toast_notifications" action from toast close button.
// The action name includes the container ID (notifications) as generated by the template.
func (c *TodoController) DismissToastNotifications(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	toastID := ctx.GetString("toast") // matches lvt-data-toast attribute
	state.Toasts.Dismiss(toastID)
	return state, nil
}

// ClearCompleted handles the "clear_completed" action.
func (c *TodoController) ClearCompleted(state TodoState, ctx *livetemplate.Context) (TodoState, error) {
	var remaining []Todo
	cleared := 0
	for _, todo := range state.Todos {
		if !todo.Completed.Checked {
			remaining = append(remaining, todo)
		} else {
			cleared++
		}
	}
	state.Todos = remaining
	if cleared > 0 {
		state.Toasts.AddSuccess("Cleared", itoa(cleared)+" completed todo(s) removed")
	} else {
		state.Toasts.AddInfo("Nothing to clear", "No completed todos found")
	}
	return state, nil
}

// Helper functions
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	if n < 0 {
		return "-" + itoa(-n)
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}

func atoi(s string) int {
	n := 0
	for _, c := range s {
		if c >= '0' && c <= '9' {
			n = n*10 + int(c-'0')
		}
	}
	return n
}

// convertTemplateSet converts a base.TemplateSet to livetemplate.TemplateSet.
// This is needed because the components library uses its own TemplateSet type
// to avoid import cycles with livetemplate.
func convertTemplateSet(set *base.TemplateSet) *livetemplate.TemplateSet {
	return &livetemplate.TemplateSet{
		FS:        set.FS,
		Pattern:   set.Pattern,
		Namespace: set.Namespace,
		Funcs:     set.Funcs,
	}
}

func main() {
	log.Println("LiveTemplate Todos with Components starting...")

	// Load configuration from environment variables
	envConfig, err := livetemplate.LoadEnvConfig()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Validate configuration
	if err := envConfig.Validate(); err != nil {
		log.Fatalf("Invalid configuration: %v", err)
	}

	// Create controller (singleton, holds dependencies)
	controller := &TodoController{}

	// Create initial state with components
	initialState := &TodoState{
		Title: "Todos with Components",
		Todos: []Todo{
			{
				ID:    1,
				Title: "Learn LiveTemplate",
				Completed: toggle.NewCheckbox("todo-1",
					toggle.WithCheckboxLabel("Learn LiveTemplate"),
				),
			},
			{
				ID:    2,
				Title: "Try the components library",
				Completed: toggle.NewCheckbox("todo-2",
					toggle.WithCheckboxLabel("Try the components library"),
				),
			},
		},
		NextID: 2,
	}

	// Create toast container (unstyled for Pico CSS)
	toasts := toast.New("notifications",
		toast.WithPosition(toast.TopRight),
		toast.WithMaxVisible(3),
	)
	toasts.SetStyled(false)
	initialState.Toasts = toasts

	// Create confirmation modal (unstyled for Pico CSS)
	deleteConfirm := modal.NewConfirm("delete_confirm",
		modal.WithConfirmTitle("Delete Todo"),
		modal.WithConfirmMessage("Are you sure you want to delete this todo?"),
		modal.WithConfirmDestructive(true),
		modal.WithConfirmText("Delete"),
		modal.WithCancelText("Cancel"),
	)
	deleteConfirm.SetStyled(false)
	initialState.DeleteConfirm = deleteConfirm

	// Get options from env config
	opts := envConfig.ToOptions()

	// Add only the component templates we need (modal, toast, toggle)
	// Using specific components instead of components.All() to avoid loading
	// unused components that may have additional function dependencies
	componentSets := []*base.TemplateSet{
		modal.Templates(),
		toast.Templates(),
		toggle.Templates(),
	}
	ltSets := make([]*livetemplate.TemplateSet, len(componentSets))
	for i, set := range componentSets {
		ltSets[i] = convertTemplateSet(set)
	}
	opts = append(opts, livetemplate.WithComponentTemplates(ltSets...))

	// Create template with component templates registered
	tmpl := livetemplate.Must(livetemplate.New("todos-components", opts...))

	// Mount handler with Controller+State pattern
	http.Handle("/", tmpl.Handle(controller, livetemplate.AsState(initialState)))

	// Serve client library (development only - use CDN in production)
	http.HandleFunc("/livetemplate-client.js", e2etest.ServeClientLibrary)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	log.Printf("Server starting on http://localhost:%s", port)
	log.Printf("Started at %s", time.Now().Format(time.RFC3339))

	if err := http.ListenAndServe(":"+port, nil); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
